x-healthcheck-config: &healthcheck-config
  interval: 10s
  timeout: 10s
  retries: 5

services:
  listener:
    build:
      context: .
      dockerfile: src/listener/Dockerfile
    depends_on:
      - mongodb
    
  mongodb:
    image: mongo:7.0.11
    ports:
      - "27017:27017"
    env_file:
      - .env
    healthcheck:
      <<: *healthcheck-config
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
    volumes:
      - mongodb_data:/data/db
        
volumes:
  mongodb_data: