x-healthcheck-config: &healthcheck-config
  interval: 10s
  timeout: 10s
  retries: 5

services:
  listener:
    build:
      context: .
      dockerfile: src/listener/Dockerfile
    depends_on:
      - postgres
      
  top_stories:
    build: 
      context: .
      dockerfile: src/top_stories/Dockerfile
    depends_on:
      - postgres
      - listener
    
  postgres:
    image: postgres:16.3-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      <<: *healthcheck-config
    volumes:
      - pg_data:/var/lib/postgresql/data
      
volumes:
  pg_data:
