services:
  listener:
    image: ghcr.io/ginruh/hckernews/listener:latest

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
