name: Create and publish images

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push listener image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/listener/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/listener:latest
